project_id = "myxsnhxorstzbrobecgw"

[functions.send-notification-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.provision-auth-user]
verify_jwt = false

[functions.linguistic-ai-analysis]
verify_jwt = false